name: TrensMinecat2
version: '${project.version}'
main: io.github.janvinas.trainmanager.TrainManager
api-version: 1.19
depend: [ Train_Carts, BKCommonLib, SignLink ]
authors: [ janitus1234 ]
commands:
  trensminecat:
    description: Main command
    usage: /tm <command>
    aliases: tm
    permission: trensminecat.x
    permission-message: You need the trensminecat.x permission to run this command.

